export { default as SystemLayout } from './SystemLayout'
export { Dashboard } from './dashboard'
export { Settings } from './settings'
export { UserProfile } from './userprofile'
export { default as Users } from './users/Users'
export { default as Company } from './company'
export { default as CompanyDetail } from './company/CompanyDetail'
export { default as CompanyRouter } from './company/CompanyRouter'
export { default as CompanyRouteWrapper } from './company/CompanyRouteWrapper'
export { default as Companies } from './companies'
export { default as Appointments } from './appointments/Appointments'
export { default as Staff } from './staff/Staff'
export { default as Products } from './products/Products'
